### PR TITLE
[For Review] Pom polish impact verification #378

### PR DESCRIPTION
**Pull request by ikeyat**
Don't merge. Just for review.
Please review https://github.com/terasolunaorg/terasoluna-tourreservation/issues/378

### CODE REVIEW

**Comment by ikeyat** [comment]
- [ ] ``terasoluna-gfw-starter-web-jsp`` should not be ``pom`` type because it  has java classes.

**Comment by ikeyat** [comment]
- [ ] ``parent`` should not be ``terasoluna-gfw-starters`` but ``terasoluna-gfw-starter-parent``.

It is easier to understand because as seen http://projects.spring.io/spring-boot/#quick-start

**Comment by btundes** [comment]
@ikeyat 
1. I think ``terasoluna-gfw-starter-web-jsp`` does not contain any java classes.Hence I have marked it as ``pom``. 
2. For your second comment above related to ``parent`` marking, I have followed the [struture explained on spring-boot](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters)

**Comment by ikeyat** [comment]
@btundes 
I updated each comment. In short,  ignore both comments.

**Pull request closed without merging**
